server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB

spring:
  main:
    web-application-type: servlet
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - logging.yml
      - monitoring.yml
      - redis.yml
  cloud:
    openfeign:
      client:
        config:
          pg-simulator:
            connect-timeout: 1000
            read-timeout: 2000

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

pg:
  simul:
    client-id: 123456
    callback-url: http://localhost:8080/api/v1/payments/callback

resilience4j:
  circuitbreaker:
    instances:
      pgSimulator:
        sliding-window-size: 20 # 최근 20건 기준으로
        failure-rate-threshold: 50 # 실패율이 50% 넘으면
        wait-duration-in-open-state: 10s # 10초 동안 오픈을 유지한다.
        permitted-number-of-calls-in-half-open-state: 3 # half-open 상태에서 3건의 요청을 통해 close 여부를 결정한다.
        automatic-transition-from-open-to-half-open-enabled: true # half-open을 사용한다.
  retry:
    instances:
      pgSimulator:
        max-attempts: 3 # 최대 재시도 횟수
        wait-duration: 1s # 재시도 간격
        enable-exponential-backoff: true # 재시도 간격 backoff 사용 여부
        exponential-backoff-multiplier: 2 # 재시도 간격 backoff 가중치


---
spring:
  config:
    activate:
      on-profile: local, test

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: qa

---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  api-docs:
    enabled: false